; MIIIME Icon Changer Configuration
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 합니다.
; This file must be saved in ANSI encoding.

[ExtractConfig]
NamingRule=2
ExtractMethod=2
SaveMethod=1
ExtractionMode=1

[Options]
BackupBeforeChange=1
ChangeDescription=1
ChangeProductName=0
LogLevel=0

[Advanced]
LogRotationSize=5242880
DeepModeGap=20
